version: '2.1'

executors:
  decks:
    docker:
      - image: makenowjust/decks:latest

commands:
  install_deps:
    description: Install Dependencies
    steps:
      - restore_cache:
          keys:
            - deps-yarn-v1-{{ checksum "yarn.lock" }}
            - deps-yarn-v1-
      - run: |
          yarn
      - save_cache:
          key: deps-yarn-v1-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules

jobs:
  check:
    executor: decks
    steps:
      - checkout
      - install_deps
      - run: yarn lint
  deploy:
    executor: decks
    steps:
      - checkout
      - install_deps
      - run: |
          yarn build --prefix-paths
      - run: |
          yarn -s gh-pages -xd public \
            -m "Update [ci skip]" \
            -r "https://MakeNowJust:$GITHUB_TOKEN@github.com/MakeNowJust/decks.git" \
            -u "TSUYUSATO Kitsune (bot) <make.just.on@gmail.com>" \
            --git "$(which git)"

workflows:
  version: 2
  check_and_deploy:
    jobs:
      - check:
          filters:
            branches:
              ignore: gh-pages
      - deploy:
          requires:
            - check
          filters:
            branches:
              only: master
